service: invoice-analyzer

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'prod'}
  region: sa-east-1  # São Paulo region
  profile: alfabet
  memorySize: 512
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}

  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'application/pdf'

functions:
  app:
    handler: lambda_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
    layer: true
    usePipenv: false

package:
  exclude:
    - venv/**
    - node_modules/**
    - .git/**
    - .gitignore
    - .DS_Store
    - '*.pdf'
    - notas/**
    - test*.py
    - debug*.py
    - analise*.py
    - scripts/**
    - CHANGELOG.md
    - relatorio*.txt
    - relatorio*.json
    - relatorio*.md